list: $/codecycler/airdesk/models/contact/columns.yaml
modelClass: Codecycler\Airdesk\Models\Contact
title: Contacts
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'codecycler/airdesk/contacts/update/:id'
