list: $/codecycler/airdesk/models/ticket/columns.yaml
modelClass: Codecycler\Airdesk\Models\Ticket
title: Tickets
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'codecycler/airdesk/tickets/update/:id'
